// GENERATED by scripts/generate_staff_console_manifest.py — do not edit by hand.
//
// The shell, and only the shell. This worker never writes a response into the cache, so no API
// payload, no customer name and no draft message can survive on the device. A staff phone is
// shared, is often unlocked, and leaves the shop; the console's offline story is therefore "the
// interface loads and tells you it cannot reach the server", never "your data is still here".

const CACHE = "staff-shell-95fc1374e7ff";

const SHELL = [
  "/staff/",
  "/staff/app.js",
  "/staff/icon.svg",
  "/staff/manifest.webmanifest",
  "/staff/src/core/api.js",
  "/staff/src/core/bands.js",
  "/staff/src/core/dom.js",
  "/staff/src/core/errors.js",
  "/staff/src/core/format.js",
  "/staff/src/core/i18n.js",
  "/staff/src/core/nav.js",
  "/staff/src/core/orderStatus.js",
  "/staff/src/core/rbac.js",
  "/staff/src/core/remedies.js",
  "/staff/src/core/reportWindow.js",
  "/staff/src/core/router.js",
  "/staff/src/core/session.js",
  "/staff/src/screens/approvals.js",
  "/staff/src/screens/assistant.js",
  "/staff/src/screens/exceptions.js",
  "/staff/src/screens/exports.js",
  "/staff/src/screens/gaps.js",
  "/staff/src/screens/incidents.js",
  "/staff/src/screens/index.js",
  "/staff/src/screens/manualSend.js",
  "/staff/src/screens/more.js",
  "/staff/src/screens/newOrder.js",
  "/staff/src/screens/orderDetail.js",
  "/staff/src/screens/orderRequests.js",
  "/staff/src/screens/orders.js",
  "/staff/src/screens/quotes.js",
  "/staff/src/screens/receipt.js",
  "/staff/src/screens/remedies.js",
  "/staff/src/screens/reports.js",
  "/staff/src/screens/shadow.js",
  "/staff/src/screens/slaBoard.js",
  "/staff/src/screens/staff.js",
  "/staff/src/screens/system.js",
  "/staff/src/screens/today.js",
  "/staff/src/ui/components.js",
  "/staff/src/ui/handoff.js",
  "/staff/src/ui/kit.js",
  "/staff/src/ui/quoting.js",
  "/staff/src/ui/sessions.js",
  "/staff/styles/base.css",
  "/staff/styles/components.css",
  "/staff/styles/kit.css",
  "/staff/styles/layout.css",
  "/staff/styles/print.css",
  "/staff/styles/tokens.css",
];

self.addEventListener("install", (event) => {
  // `cache: "reload"` on every shell request, and the cache name being a fingerprint of the files
  // is exactly why it is needed. `cache.addAll(SHELL)` uses the default HTTP cache mode, so the
  // browser is free to satisfy each request from its own HTTP cache -- which on the tablet that
  // was running the console five minutes before a deploy still holds the previous modules. The new
  // fingerprinted cache would then be populated with pre-deploy JavaScript and, being correctly
  // named for the new build, never revalidated: old code against a new API, indefinitely, on that
  // one device. "reload" bypasses the HTTP cache and takes the files from the network.
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(SHELL.map((path) => new Request(path, { cache: "reload" })))),
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  // Anything outside the shell path — every API call included — is left entirely alone. The worker
  // does not proxy it, does not read it, and has no branch that could cache it.
  if (event.request.method !== "GET") return;
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith("/staff/")) return;

  // `fetch` rejects on a transport failure and resolves on an HTTP error, so `.catch` alone let a
  // 502 or a 503 from the proxy through to the page as though it were the module. The browser then
  // fails to parse an error page as JavaScript and the console is blank, with a good copy of the
  // file sitting in the cache the whole time. An error response is a failure to serve the shell,
  // and is treated as one.
  const fallback = () => caches.match(event.request).then((hit) => hit || Response.error());
  event.respondWith(
    fetch(event.request)
      .then((response) => (response.ok ? response : fallback()))
      .catch(fallback),
  );
});
