// GENERATED by scripts/generate_staff_console_manifest.py — do not edit by hand.
//
// The shell, and only the shell. This worker never writes a response into the cache, so no API
// payload, no customer name and no draft message can survive on the device. A staff phone is
// shared, is often unlocked, and leaves the shop; the console's offline story is therefore "the
// interface loads and tells you it cannot reach the server", never "your data is still here".

const CACHE = "staff-shell-580526ef2a09";

const SHELL = [
  "/staff/",
  "/staff/app.js",
  "/staff/icon.svg",
  "/staff/manifest.webmanifest",
  "/staff/src/core/api.js",
  "/staff/src/core/dom.js",
  "/staff/src/core/errors.js",
  "/staff/src/core/format.js",
  "/staff/src/core/i18n.js",
  "/staff/src/core/rbac.js",
  "/staff/src/core/router.js",
  "/staff/src/core/session.js",
  "/staff/src/screens/approvals.js",
  "/staff/src/screens/assistant.js",
  "/staff/src/screens/exceptions.js",
  "/staff/src/screens/gaps.js",
  "/staff/src/screens/incidents.js",
  "/staff/src/screens/index.js",
  "/staff/src/screens/manualSend.js",
  "/staff/src/screens/orderDetail.js",
  "/staff/src/screens/orderRequests.js",
  "/staff/src/screens/orders.js",
  "/staff/src/screens/quotes.js",
  "/staff/src/screens/shadow.js",
  "/staff/src/screens/staff.js",
  "/staff/src/screens/system.js",
  "/staff/src/screens/today.js",
  "/staff/src/ui/components.js",
  "/staff/styles/base.css",
  "/staff/styles/components.css",
  "/staff/styles/layout.css",
  "/staff/styles/print.css",
  "/staff/styles/tokens.css",
];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(SHELL)));
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  // Anything outside the shell path — every API call included — is left entirely alone. The worker
  // does not proxy it, does not read it, and has no branch that could cache it.
  if (event.request.method !== "GET") return;
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith("/staff/")) return;

  event.respondWith(
    fetch(event.request).catch(() =>
      caches.match(event.request).then((hit) => hit || Response.error()),
    ),
  );
});
