// Generated by scripts/generate_agent_tool_plugin.py. Do not hand edit.
// Model parameters intentionally exclude all path/header binding fields.

export const OPERATIONS = {
  "catalogResolve": {
  "operationId": "catalogResolve",
  "toolName": "laundry_catalog_resolve",
  "method": "POST",
  "path": "/agent/v1/catalog:resolve",
  "summary": "Resolve customer wording to candidate services without selecting a final service.",
  "pathParameters": [],
  "headerParameters": [],
  "parameters": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "query",
      "locale"
    ],
    "properties": {
      "query": {
        "type": "string",
        "minLength": 1,
        "maxLength": 300
      },
      "locale": {
        "const": "vi-VN"
      },
      "known_attributes": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "estimated_quantity": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)(\\.[0-9]{1,3})?$"
          },
          "unit": {
            "type": "string",
            "enum": [
              "KG",
              "ITEM",
              "PAIR",
              "SET",
              "ANIMAL_PLUSH_ITEM",
              "CASE",
              "M2"
            ]
          }
        }
      }
    }
  },
  "successStatus": 200,
  "successResponse": {
    "type": "object",
    "unevaluatedProperties": false,
    "allOf": [
      {
        "type": "object",
        "required": [
          "ok",
          "trace_id",
          "decision"
        ],
        "properties": {
          "ok": {
            "const": true
          },
          "trace_id": {
            "type": "string",
            "minLength": 8,
            "maxLength": 80
          },
          "decision": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "outcome",
              "reason_codes",
              "obligations",
              "policy_version",
              "snapshot_hash"
            ],
            "properties": {
              "outcome": {
                "type": "string",
                "enum": [
                  "ALLOW",
                  "REQUIRE_HUMAN",
                  "DENY"
                ]
              },
              "reason_codes": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "obligations": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "policy_version": {
                "type": "string",
                "minLength": 1,
                "maxLength": 80
              },
              "snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            }
          }
        }
      },
      {
        "type": "object",
        "required": [
          "data"
        ],
        "properties": {
          "data": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "candidates"
            ],
            "properties": {
              "candidates": {
                "type": "array",
                "maxItems": 5,
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "service_code",
                    "service_version",
                    "display_name",
                    "compatible_units",
                    "confidence_band"
                  ],
                  "properties": {
                    "service_code": {
                      "type": "string",
                      "pattern": "^[A-Z0-9_]+$"
                    },
                    "service_version": {
                      "type": "string"
                    },
                    "display_name": {
                      "type": "string"
                    },
                    "compatible_units": {
                      "type": "array",
                      "minItems": 1,
                      "items": {
                        "type": "string",
                        "enum": [
                          "KG",
                          "ITEM",
                          "PAIR",
                          "SET",
                          "ANIMAL_PLUSH_ITEM",
                          "CASE",
                          "M2"
                        ]
                      }
                    },
                    "confidence_band": {
                      "type": "string",
                      "enum": [
                        "HIGH",
                        "MEDIUM",
                        "LOW"
                      ]
                    },
                    "clarification_key": {
                      "type": [
                        "string",
                        "null"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    ]
  }
},
  "orderRequestCreate": {
  "operationId": "orderRequestCreate",
  "toolName": "laundry_order_request_create",
  "method": "POST",
  "path": "/agent/v1/order-requests",
  "summary": "Create an intake draft bound to the authenticated channel contact.",
  "pathParameters": [],
  "headerParameters": [
    "Idempotency-Key"
  ],
  "parameters": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "customer_intent",
      "locale",
      "source_provider_message_ids"
    ],
    "properties": {
      "customer_intent": {
        "type": "string",
        "minLength": 1,
        "maxLength": 500
      },
      "locale": {
        "const": "vi-VN"
      },
      "source_provider_message_ids": {
        "type": "array",
        "minItems": 1,
        "maxItems": 10,
        "uniqueItems": true,
        "description": "Every ID must belong to the authenticated bound channel conversation; the server rejects cross-conversation or unknown IDs.",
        "items": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        }
      }
    }
  },
  "successStatus": 201,
  "successResponse": {
    "type": "object",
    "unevaluatedProperties": false,
    "allOf": [
      {
        "type": "object",
        "required": [
          "ok",
          "trace_id",
          "decision"
        ],
        "properties": {
          "ok": {
            "const": true
          },
          "trace_id": {
            "type": "string",
            "minLength": 8,
            "maxLength": 80
          },
          "decision": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "outcome",
              "reason_codes",
              "obligations",
              "policy_version",
              "snapshot_hash"
            ],
            "properties": {
              "outcome": {
                "type": "string",
                "enum": [
                  "ALLOW",
                  "REQUIRE_HUMAN",
                  "DENY"
                ]
              },
              "reason_codes": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "obligations": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "policy_version": {
                "type": "string",
                "minLength": 1,
                "maxLength": 80
              },
              "snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            }
          }
        }
      },
      {
        "type": "object",
        "required": [
          "data"
        ],
        "properties": {
          "data": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "order_request_id",
              "row_version",
              "status"
            ],
            "properties": {
              "order_request_id": {
                "type": "string",
                "format": "uuid"
              },
              "row_version": {
                "type": "integer",
                "minimum": 1
              },
              "status": {
                "const": "DRAFT"
              }
            }
          }
        }
      }
    ]
  }
},
  "orderRequestRecordCustomerFacts": {
  "operationId": "orderRequestRecordCustomerFacts",
  "toolName": "laundry_order_request_record_customer_facts",
  "method": "POST",
  "path": "/agent/v1/order-requests/{order_request_id}:record-customer-facts",
  "summary": "Record an allowlisted fact stated by the bound customer.",
  "pathParameters": [
    "order_request_id"
  ],
  "headerParameters": [
    "Idempotency-Key",
    "If-Match"
  ],
  "parameters": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "facts"
    ],
    "properties": {
      "facts": {
        "type": "array",
        "minItems": 1,
        "maxItems": 10,
        "items": {
          "oneOf": [
            {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "fact_type",
                "service_text",
                "source_provider_message_id"
              ],
              "properties": {
                "fact_type": {
                  "const": "SERVICE_TEXT"
                },
                "service_text": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 300
                },
                "source_provider_message_id": {
                  "type": "string"
                }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "fact_type",
                "quantity",
                "unit",
                "source_provider_message_id"
              ],
              "properties": {
                "fact_type": {
                  "const": "ESTIMATED_QUANTITY"
                },
                "quantity": {
                  "type": "string",
                  "pattern": "^(0|[1-9][0-9]*)(\\.[0-9]{1,3})?$"
                },
                "unit": {
                  "type": "string",
                  "enum": [
                    "KG",
                    "ITEM",
                    "PAIR",
                    "SET",
                    "ANIMAL_PLUSH_ITEM",
                    "CASE",
                    "M2"
                  ]
                },
                "source_provider_message_id": {
                  "type": "string"
                }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "fact_type",
                "fulfillment_mode",
                "source_provider_message_id"
              ],
              "properties": {
                "fact_type": {
                  "const": "FULFILLMENT_MODE"
                },
                "fulfillment_mode": {
                  "type": "string",
                  "enum": [
                    "SELF_DROP_SELF_COLLECT",
                    "PICKUP_AND_RETURN",
                    "PICKUP_ONLY",
                    "RETURN_ONLY"
                  ]
                },
                "source_provider_message_id": {
                  "type": "string"
                }
              }
            },
            {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "fact_type",
                "address_text",
                "source_provider_message_id"
              ],
              "properties": {
                "fact_type": {
                  "const": "CUSTOMER_ADDRESS_TEXT"
                },
                "address_text": {
                  "type": "string",
                  "minLength": 5,
                  "maxLength": 500
                },
                "source_provider_message_id": {
                  "type": "string"
                }
              }
            }
          ]
        }
      }
    }
  },
  "successStatus": 200,
  "successResponse": {
    "type": "object",
    "unevaluatedProperties": false,
    "allOf": [
      {
        "type": "object",
        "required": [
          "ok",
          "trace_id",
          "decision"
        ],
        "properties": {
          "ok": {
            "const": true
          },
          "trace_id": {
            "type": "string",
            "minLength": 8,
            "maxLength": 80
          },
          "decision": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "outcome",
              "reason_codes",
              "obligations",
              "policy_version",
              "snapshot_hash"
            ],
            "properties": {
              "outcome": {
                "type": "string",
                "enum": [
                  "ALLOW",
                  "REQUIRE_HUMAN",
                  "DENY"
                ]
              },
              "reason_codes": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "obligations": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "policy_version": {
                "type": "string",
                "minLength": 1,
                "maxLength": 80
              },
              "snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            }
          }
        }
      },
      {
        "type": "object",
        "required": [
          "data"
        ],
        "properties": {
          "data": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "order_request_id",
              "row_version",
              "accepted_fact_count",
              "unresolved_fact_types"
            ],
            "properties": {
              "order_request_id": {
                "type": "string",
                "format": "uuid"
              },
              "row_version": {
                "type": "integer"
              },
              "accepted_fact_count": {
                "type": "integer",
                "minimum": 0
              },
              "unresolved_fact_types": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    ]
  }
},
  "quoteEstimate": {
  "operationId": "quoteEstimate",
  "toolName": "laundry_quote_estimate",
  "method": "POST",
  "path": "/agent/v1/order-requests/{order_request_id}/quotes:estimate",
  "summary": "Compute a provisional customer estimate for the bound request.",
  "pathParameters": [
    "order_request_id"
  ],
  "headerParameters": [
    "Idempotency-Key",
    "If-Match"
  ],
  "parameters": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "lines",
      "fulfillment"
    ],
    "properties": {
      "lines": {
        "type": "array",
        "minItems": 1,
        "maxItems": 50,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "service_code",
            "quantity_basis",
            "quantity",
            "unit"
          ],
          "properties": {
            "service_code": {
              "type": "string",
              "pattern": "^[A-Z0-9_]+$"
            },
            "quantity_basis": {
              "type": "string",
              "enum": [
                "CUSTOMER_ESTIMATE"
              ],
              "x-canonical-subset": true,
              "description": "Public agent estimates may use only customer-provided estimated quantity."
            },
            "quantity": {
              "type": "string",
              "pattern": "^(0|[1-9][0-9]*)(\\.[0-9]{1,3})?$"
            },
            "unit": {
              "type": "string",
              "enum": [
                "KG",
                "ITEM",
                "PAIR",
                "SET",
                "ANIMAL_PLUSH_ITEM",
                "CASE",
                "M2"
              ]
            }
          }
        }
      },
      "fulfillment": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "mode"
        ],
        "properties": {
          "mode": {
            "type": "string",
            "enum": [
              "SELF_DROP_SELF_COLLECT",
              "PICKUP_AND_RETURN",
              "PICKUP_ONLY",
              "RETURN_ONLY"
            ]
          },
          "planned_transport_weight_kg": {
            "type": "string",
            "pattern": "^(0|[1-9][0-9]*)(\\.[0-9]{1,3})?$"
          }
        }
      }
    }
  },
  "successStatus": 200,
  "successResponse": {
    "type": "object",
    "unevaluatedProperties": false,
    "allOf": [
      {
        "type": "object",
        "required": [
          "ok",
          "trace_id",
          "decision"
        ],
        "properties": {
          "ok": {
            "const": true
          },
          "trace_id": {
            "type": "string",
            "minLength": 8,
            "maxLength": 80
          },
          "decision": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "outcome",
              "reason_codes",
              "obligations",
              "policy_version",
              "snapshot_hash"
            ],
            "properties": {
              "outcome": {
                "type": "string",
                "enum": [
                  "ALLOW",
                  "REQUIRE_HUMAN",
                  "DENY"
                ]
              },
              "reason_codes": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "obligations": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "policy_version": {
                "type": "string",
                "minLength": 1,
                "maxLength": 80
              },
              "snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            }
          }
        }
      },
      {
        "type": "object",
        "required": [
          "data"
        ],
        "properties": {
          "data": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "quote_id",
              "quote_revision_id",
              "revision",
              "finality",
              "list_service_subtotal_vnd",
              "discount_amount_vnd",
              "net_service_subtotal_vnd",
              "display_total_vnd",
              "tax_treatment",
              "promotion_status",
              "required_approvals",
              "assumptions",
              "snapshot_hash"
            ],
            "properties": {
              "quote_id": {
                "type": "string",
                "format": "uuid"
              },
              "quote_revision_id": {
                "type": "string",
                "format": "uuid"
              },
              "revision": {
                "type": "integer",
                "minimum": 1
              },
              "finality": {
                "const": "ESTIMATE"
              },
              "pricebook_version": {
                "type": "string"
              },
              "promotion_version": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "list_service_subtotal_vnd": {
                "type": "integer",
                "minimum": 0,
                "maximum": 1000000000
              },
              "discount_amount_vnd": {
                "type": "integer",
                "minimum": 0,
                "maximum": 1000000000
              },
              "net_service_subtotal_vnd": {
                "type": "integer",
                "minimum": 0,
                "maximum": 1000000000
              },
              "delivery_fee_vnd": {
                "oneOf": [
                  {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 1000000000
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "display_total_vnd": {
                "oneOf": [
                  {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 1000000000
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "tax_treatment": {
                "type": "string",
                "enum": [
                  "UNVERIFIED",
                  "INCLUDED",
                  "EXCLUDED",
                  "NOT_APPLICABLE"
                ]
              },
              "promotion_status": {
                "type": "string",
                "enum": [
                  "NOT_APPLICABLE",
                  "PROVISIONAL",
                  "ELIGIBLE",
                  "INELIGIBLE",
                  "REQUIRES_HUMAN"
                ]
              },
              "promotion_eligibility_event": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "promotion_eligibility_at": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time"
              },
              "vehicle_recommendation": {
                "type": [
                  "string",
                  "null"
                ],
                "enum": [
                  "MOTORCYCLE",
                  "CAR",
                  null
                ]
              },
              "required_approvals": {
                "type": "array",
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "assumptions": {
                "type": "array",
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            }
          }
        }
      }
    ]
  }
},
  "deliveryEvaluate": {
  "operationId": "deliveryEvaluate",
  "toolName": "laundry_delivery_evaluate",
  "method": "POST",
  "path": "/agent/v1/order-requests/{order_request_id}/delivery:evaluate",
  "summary": "Evaluate delivery using the request-bound address and distance evidence.",
  "pathParameters": [
    "order_request_id"
  ],
  "headerParameters": [],
  "parameters": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "fulfillment_mode"
    ],
    "properties": {
      "fulfillment_mode": {
        "type": "string",
        "enum": [
          "SELF_DROP_SELF_COLLECT",
          "PICKUP_AND_RETURN",
          "PICKUP_ONLY",
          "RETURN_ONLY"
        ]
      },
      "planned_transport_weight_kg": {
        "type": "string",
        "pattern": "^(0|[1-9][0-9]*)(\\.[0-9]{1,3})?$"
      }
    }
  },
  "successStatus": 200,
  "successResponse": {
    "type": "object",
    "unevaluatedProperties": false,
    "allOf": [
      {
        "type": "object",
        "required": [
          "ok",
          "trace_id",
          "decision"
        ],
        "properties": {
          "ok": {
            "const": true
          },
          "trace_id": {
            "type": "string",
            "minLength": 8,
            "maxLength": 80
          },
          "decision": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "outcome",
              "reason_codes",
              "obligations",
              "policy_version",
              "snapshot_hash"
            ],
            "properties": {
              "outcome": {
                "type": "string",
                "enum": [
                  "ALLOW",
                  "REQUIRE_HUMAN",
                  "DENY"
                ]
              },
              "reason_codes": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "obligations": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "policy_version": {
                "type": "string",
                "minLength": 1,
                "maxLength": 80
              },
              "snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            }
          }
        }
      },
      {
        "type": "object",
        "required": [
          "data"
        ],
        "properties": {
          "data": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "distance_status",
              "fee_status",
              "vehicle_recommendation",
              "requires_human"
            ],
            "properties": {
              "distance_status": {
                "type": "string",
                "enum": [
                  "VERIFIED",
                  "UNVERIFIED",
                  "STALE",
                  "NOT_REQUIRED"
                ]
              },
              "distance_km": {
                "oneOf": [
                  {
                    "type": "string",
                    "pattern": "^(0|[1-9][0-9]*)(\\.[0-9]{1,3})?$"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "fee_status": {
                "type": "string",
                "enum": [
                  "RESOLVED",
                  "REQUIRES_HUMAN",
                  "NOT_REQUIRED"
                ]
              },
              "delivery_fee_vnd": {
                "oneOf": [
                  {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 1000000000
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "vehicle_recommendation": {
                "type": "string",
                "enum": [
                  "MOTORCYCLE",
                  "CAR",
                  "STAFF_PLAN_REQUIRED",
                  "NOT_REQUIRED"
                ]
              },
              "requires_human": {
                "type": "boolean"
              }
            }
          }
        }
      }
    ]
  }
},
  "capacityCheck": {
  "operationId": "capacityCheck",
  "toolName": "laundry_capacity_check",
  "method": "POST",
  "path": "/agent/v1/order-requests/{order_request_id}/capacity:check",
  "summary": "Read a non-binding capacity advisory; never reserves or confirms a slot.",
  "pathParameters": [
    "order_request_id"
  ],
  "headerParameters": [],
  "parameters": {
    "type": "object",
    "additionalProperties": false,
    "description": "Service scope, quantity and current intake/quote revision are derived from the path-bound order request.",
    "properties": {
      "requested_ready_at": {
        "type": [
          "string",
          "null"
        ],
        "format": "date-time",
        "description": "Customer-requested time only; it is never a reservation or promise."
      }
    }
  },
  "successStatus": 200,
  "successResponse": {
    "type": "object",
    "unevaluatedProperties": false,
    "allOf": [
      {
        "type": "object",
        "required": [
          "ok",
          "trace_id",
          "decision"
        ],
        "properties": {
          "ok": {
            "const": true
          },
          "trace_id": {
            "type": "string",
            "minLength": 8,
            "maxLength": 80
          },
          "decision": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "outcome",
              "reason_codes",
              "obligations",
              "policy_version",
              "snapshot_hash"
            ],
            "properties": {
              "outcome": {
                "type": "string",
                "enum": [
                  "ALLOW",
                  "REQUIRE_HUMAN",
                  "DENY"
                ]
              },
              "reason_codes": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "obligations": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "policy_version": {
                "type": "string",
                "minLength": 1,
                "maxLength": 80
              },
              "snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            }
          }
        }
      },
      {
        "type": "object",
        "required": [
          "data"
        ],
        "properties": {
          "data": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "advisory",
              "slot_confirmed",
              "required_approval"
            ],
            "properties": {
              "advisory": {
                "type": "string",
                "enum": [
                  "LIKELY_AVAILABLE",
                  "CONSTRAINED",
                  "UNKNOWN"
                ]
              },
              "advisory_ready_window_start": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time"
              },
              "advisory_ready_window_end": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time"
              },
              "slot_confirmed": {
                "const": false
              },
              "required_approval": {
                "const": "SLOT_CONFIRMATION"
              }
            }
          }
        }
      }
    ]
  }
},
  "messageDraftCreate": {
  "operationId": "messageDraftCreate",
  "toolName": "laundry_message_draft_create",
  "method": "POST",
  "path": "/agent/v1/order-requests/{order_request_id}/message-drafts",
  "summary": "Request a scoped message draft; this operation cannot send.",
  "pathParameters": [
    "order_request_id"
  ],
  "headerParameters": [
    "Idempotency-Key"
  ],
  "parameters": {
    "description": "The request never accepts a template or business-resource ID. For deterministic\nkinds, the server selects the current published template and the current bound\nresource/facts from message kind, locale, stage and effective time.\n",
    "oneOf": [
      {
        "title": "Deterministic server-rendered message",
        "type": "object",
        "additionalProperties": false,
        "required": [
          "message_kind",
          "locale"
        ],
        "properties": {
          "message_kind": {
            "type": "string",
            "enum": [
              "LIST_PRICE_INFO",
              "INTAKE_RECEIPT",
              "INCIDENT_RECEIPT",
              "ORDER_STATUS",
              "APPROVED_QUOTE_PRESENTATION",
              "APPROVED_SLOT_PRESENTATION"
            ]
          },
          "locale": {
            "const": "vi-VN"
          }
        }
      },
      {
        "title": "Grounded intake question draft",
        "type": "object",
        "additionalProperties": false,
        "required": [
          "message_kind",
          "locale",
          "customer_question_provider_message_id"
        ],
        "properties": {
          "message_kind": {
            "const": "INTAKE_FACT_REQUEST"
          },
          "locale": {
            "const": "vi-VN"
          },
          "customer_question_provider_message_id": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200,
            "description": "Must belong to the authenticated bound conversation."
          }
        }
      },
      {
        "title": "Human-only free-form transactional draft",
        "type": "object",
        "additionalProperties": false,
        "required": [
          "message_kind",
          "locale",
          "customer_question_provider_message_id"
        ],
        "properties": {
          "message_kind": {
            "const": "FREE_FORM_TRANSACTIONAL"
          },
          "locale": {
            "const": "vi-VN"
          },
          "customer_question_provider_message_id": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200,
            "description": "Must belong to the authenticated bound conversation."
          }
        }
      }
    ]
  },
  "successStatus": 201,
  "successResponse": {
    "type": "object",
    "unevaluatedProperties": false,
    "allOf": [
      {
        "type": "object",
        "required": [
          "ok",
          "trace_id",
          "decision"
        ],
        "properties": {
          "ok": {
            "const": true
          },
          "trace_id": {
            "type": "string",
            "minLength": 8,
            "maxLength": 80
          },
          "decision": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "outcome",
              "reason_codes",
              "obligations",
              "policy_version",
              "snapshot_hash"
            ],
            "properties": {
              "outcome": {
                "type": "string",
                "enum": [
                  "ALLOW",
                  "REQUIRE_HUMAN",
                  "DENY"
                ]
              },
              "reason_codes": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "obligations": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "policy_version": {
                "type": "string",
                "minLength": 1,
                "maxLength": 80
              },
              "snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            }
          }
        }
      },
      {
        "type": "object",
        "required": [
          "data"
        ],
        "properties": {
          "data": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "message_draft_id",
              "revision",
              "message_kind",
              "content",
              "content_hash",
              "template_id",
              "template_version",
              "fact_refs",
              "rendered_slots_hash",
              "policy_snapshot_hash",
              "send_capability"
            ],
            "properties": {
              "message_draft_id": {
                "type": "string",
                "format": "uuid"
              },
              "revision": {
                "type": "integer",
                "minimum": 1
              },
              "message_kind": {
                "type": "string",
                "enum": [
                  "LIST_PRICE_INFO",
                  "INTAKE_FACT_REQUEST",
                  "INTAKE_RECEIPT",
                  "INCIDENT_RECEIPT",
                  "ORDER_STATUS",
                  "APPROVED_QUOTE_PRESENTATION",
                  "APPROVED_SLOT_PRESENTATION",
                  "FREE_FORM_TRANSACTIONAL"
                ]
              },
              "template_id": {
                "type": [
                  "string",
                  "null"
                ],
                "description": "Server-selected published template; null only for a human-only free-form draft."
              },
              "template_version": {
                "type": [
                  "string",
                  "null"
                ],
                "description": "Immutable server-selected version; null only for a human-only free-form draft."
              },
              "fact_refs": {
                "type": "array",
                "maxItems": 30,
                "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "fact_type",
                    "resource_type",
                    "resource_id",
                    "resource_version",
                    "value_hash",
                    "contact_scope_hash",
                    "effective_at",
                    "current"
                  ],
                  "properties": {
                    "fact_type": {
                      "type": "string",
                      "enum": [
                        "CATALOG_PRICE",
                        "ORDER_REQUEST_RECEIPT",
                        "INCIDENT_RECEIPT",
                        "ORDER_STATUS",
                        "QUOTE_REVISION",
                        "SLOT_PROMISE",
                        "CUSTOMER_MESSAGE"
                      ]
                    },
                    "resource_type": {
                      "type": "string",
                      "enum": [
                        "SERVICE_VERSION",
                        "PRICE_RULE",
                        "ORDER_REQUEST",
                        "INCIDENT",
                        "ORDER",
                        "QUOTE_REVISION",
                        "SLA_PROMISE",
                        "PROVIDER_MESSAGE"
                      ]
                    },
                    "resource_id": {
                      "type": "string",
                      "format": "uuid"
                    },
                    "resource_version": {
                      "type": "integer",
                      "minimum": 1
                    },
                    "value_hash": {
                      "type": "string",
                      "pattern": "^sha256:[0-9a-f]{64}$"
                    },
                    "contact_scope_hash": {
                      "type": "string",
                      "pattern": "^sha256:[0-9a-f]{64}$"
                    },
                    "effective_at": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "expires_at": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "format": "date-time"
                    },
                    "current": {
                      "const": true
                    }
                  }
                }
              },
              "content": {
                "type": "string",
                "maxLength": 4000
              },
              "content_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              },
              "rendered_slots_hash": {
                "$ref": "#/components/schemas/Sha256",
                "description": "Hash of canonical JCS slot values; an empty slot object is still hashed."
              },
              "policy_snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              },
              "send_capability": {
                "type": "string",
                "enum": [
                  "NEVER",
                  "HUMAN_APPROVAL_REQUIRED",
                  "POLICY_ELIGIBLE"
                ]
              }
            },
            "allOf": [
              {
                "if": {
                  "type": "object",
                  "properties": {
                    "message_kind": {
                      "enum": [
                        "LIST_PRICE_INFO",
                        "INTAKE_RECEIPT",
                        "INCIDENT_RECEIPT",
                        "ORDER_STATUS",
                        "APPROVED_QUOTE_PRESENTATION",
                        "APPROVED_SLOT_PRESENTATION"
                      ]
                    }
                  },
                  "required": [
                    "message_kind"
                  ]
                },
                "then": {
                  "type": "object",
                  "properties": {
                    "template_id": {
                      "type": "string",
                      "minLength": 1
                    },
                    "template_version": {
                      "type": "string",
                      "minLength": 1
                    },
                    "fact_refs": {
                      "type": "array",
                      "minItems": 1
                    }
                  }
                }
              }
            ]
          }
        }
      }
    ]
  }
},
  "publicOrderStatusGet": {
  "operationId": "publicOrderStatusGet",
  "toolName": "laundry_public_order_status_get",
  "method": "GET",
  "path": "/agent/v1/orders/{public_code}/status",
  "summary": "Return a redacted status only when verified channel ownership also matches.",
  "pathParameters": [
    "public_code"
  ],
  "headerParameters": [],
  "parameters": {
    "type": "object",
    "additionalProperties": false,
    "properties": {}
  },
  "successStatus": 200,
  "successResponse": {
    "type": "object",
    "unevaluatedProperties": false,
    "allOf": [
      {
        "type": "object",
        "required": [
          "ok",
          "trace_id",
          "decision"
        ],
        "properties": {
          "ok": {
            "const": true
          },
          "trace_id": {
            "type": "string",
            "minLength": 8,
            "maxLength": 80
          },
          "decision": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "outcome",
              "reason_codes",
              "obligations",
              "policy_version",
              "snapshot_hash"
            ],
            "properties": {
              "outcome": {
                "type": "string",
                "enum": [
                  "ALLOW",
                  "REQUIRE_HUMAN",
                  "DENY"
                ]
              },
              "reason_codes": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "obligations": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "policy_version": {
                "type": "string",
                "minLength": 1,
                "maxLength": 80
              },
              "snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            }
          }
        }
      },
      {
        "type": "object",
        "required": [
          "data"
        ],
        "properties": {
          "data": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "public_code",
              "status_label",
              "last_status_at"
            ],
            "properties": {
              "public_code": {
                "type": "string"
              },
              "status_label": {
                "type": "string",
                "enum": [
                  "REQUEST_RECEIVED",
                  "WAITING_STORE_CONFIRMATION",
                  "IN_PROCESS",
                  "READY_AT_STORE",
                  "OUT_FOR_DELIVERY",
                  "COMPLETED",
                  "STAFF_CONTACT_REQUIRED"
                ]
              },
              "last_status_at": {
                "type": "string",
                "format": "date-time"
              },
              "ready_window_start": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time"
              },
              "ready_window_end": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time"
              }
            }
          }
        }
      }
    ]
  }
},
  "incidentOpen": {
  "operationId": "incidentOpen",
  "toolName": "laundry_incident_open",
  "method": "POST",
  "path": "/agent/v1/order-requests/{order_request_id}/incidents:open",
  "summary": "Store the bound customer's allegation; never decide fault or remedy.",
  "pathParameters": [
    "order_request_id"
  ],
  "headerParameters": [
    "Idempotency-Key"
  ],
  "parameters": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "allegation_type",
      "statement",
      "source_provider_message_ids"
    ],
    "properties": {
      "allegation_type": {
        "type": "string",
        "enum": [
          "QUALITY",
          "DELAY",
          "LOSS",
          "DAMAGE",
          "DELIVERY",
          "BILLING",
          "OTHER"
        ]
      },
      "statement": {
        "type": "string",
        "minLength": 1,
        "maxLength": 2000
      },
      "source_provider_message_ids": {
        "type": "array",
        "minItems": 1,
        "maxItems": 20,
        "uniqueItems": true,
        "description": "Every ID must belong to the authenticated bound channel conversation.",
        "items": {
          "type": "string"
        }
      },
      "evidence_tokens": {
        "type": "array",
        "maxItems": 10,
        "description": "Server-issued upload tokens already bound to this contact/conversation; arbitrary object keys are rejected.",
        "items": {
          "type": "string",
          "maxLength": 200
        }
      }
    }
  },
  "successStatus": 201,
  "successResponse": {
    "type": "object",
    "unevaluatedProperties": false,
    "allOf": [
      {
        "type": "object",
        "required": [
          "ok",
          "trace_id",
          "decision"
        ],
        "properties": {
          "ok": {
            "const": true
          },
          "trace_id": {
            "type": "string",
            "minLength": 8,
            "maxLength": 80
          },
          "decision": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "outcome",
              "reason_codes",
              "obligations",
              "policy_version",
              "snapshot_hash"
            ],
            "properties": {
              "outcome": {
                "type": "string",
                "enum": [
                  "ALLOW",
                  "REQUIRE_HUMAN",
                  "DENY"
                ]
              },
              "reason_codes": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "obligations": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "policy_version": {
                "type": "string",
                "minLength": 1,
                "maxLength": 80
              },
              "snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            }
          }
        }
      },
      {
        "type": "object",
        "required": [
          "data"
        ],
        "properties": {
          "data": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "incident_id",
              "status",
              "fault_decided",
              "remedy_decided"
            ],
            "properties": {
              "incident_id": {
                "type": "string",
                "format": "uuid"
              },
              "status": {
                "const": "OPEN"
              },
              "fault_decided": {
                "const": false
              },
              "remedy_decided": {
                "const": false
              }
            }
          }
        }
      }
    ]
  }
},
  "approvalRequestCreate": {
  "operationId": "approvalRequestCreate",
  "toolName": "laundry_approval_request_create",
  "method": "POST",
  "path": "/agent/v1/order-requests/{order_request_id}/approvals:request",
  "summary": "Request policy-derived human approval for an exact immutable snapshot.",
  "pathParameters": [
    "order_request_id"
  ],
  "headerParameters": [
    "Idempotency-Key"
  ],
  "parameters": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "action",
      "resource_type",
      "resource_id",
      "resource_version",
      "snapshot_hash",
      "rendered_hash"
    ],
    "properties": {
      "action": {
        "type": "string",
        "enum": [
          "PRESENT_QUOTE",
          "CONFIRM_SLOT",
          "SET_RANGE_PRICE",
          "SET_DELIVERY_FEE",
          "APPLY_PROMOTION",
          "SEND_MESSAGE",
          "ACCEPT_ORDER"
        ]
      },
      "resource_type": {
        "type": "string",
        "enum": [
          "QUOTE_REVISION",
          "SLOT_PROPOSAL",
          "DELIVERY_FEE_PROPOSAL",
          "MESSAGE_DRAFT",
          "ORDER_REQUEST"
        ]
      },
      "resource_id": {
        "type": "string",
        "format": "uuid",
        "description": "Must be a current child resource of the path-bound order request."
      },
      "resource_version": {
        "type": "integer",
        "minimum": 1
      },
      "snapshot_hash": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      },
      "rendered_hash": {
        "type": "string",
        "pattern": "^sha256:[0-9a-f]{64}$"
      }
    },
    "allOf": [
      {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "action": {
                "const": "PRESENT_QUOTE"
              },
              "resource_type": {
                "const": "QUOTE_REVISION"
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "action": {
                "const": "CONFIRM_SLOT"
              },
              "resource_type": {
                "const": "SLOT_PROPOSAL"
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "action": {
                "const": "SET_RANGE_PRICE"
              },
              "resource_type": {
                "const": "QUOTE_REVISION"
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "action": {
                "const": "SET_DELIVERY_FEE"
              },
              "resource_type": {
                "const": "DELIVERY_FEE_PROPOSAL"
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "action": {
                "const": "APPLY_PROMOTION"
              },
              "resource_type": {
                "const": "QUOTE_REVISION"
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "action": {
                "const": "SEND_MESSAGE"
              },
              "resource_type": {
                "const": "MESSAGE_DRAFT"
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "action": {
                "const": "ACCEPT_ORDER"
              },
              "resource_type": {
                "const": "ORDER_REQUEST"
              }
            }
          }
        ]
      }
    ]
  },
  "successStatus": 201,
  "successResponse": {
    "type": "object",
    "unevaluatedProperties": false,
    "allOf": [
      {
        "type": "object",
        "required": [
          "ok",
          "trace_id",
          "decision"
        ],
        "properties": {
          "ok": {
            "const": true
          },
          "trace_id": {
            "type": "string",
            "minLength": 8,
            "maxLength": 80
          },
          "decision": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "outcome",
              "reason_codes",
              "obligations",
              "policy_version",
              "snapshot_hash"
            ],
            "properties": {
              "outcome": {
                "type": "string",
                "enum": [
                  "ALLOW",
                  "REQUIRE_HUMAN",
                  "DENY"
                ]
              },
              "reason_codes": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "obligations": {
                "type": "array",
                "maxItems": 20,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "policy_version": {
                "type": "string",
                "minLength": 1,
                "maxLength": 80
              },
              "snapshot_hash": {
                "type": "string",
                "pattern": "^sha256:[0-9a-f]{64}$"
              }
            }
          }
        }
      },
      {
        "type": "object",
        "required": [
          "data"
        ],
        "properties": {
          "data": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "approval_request_id",
              "status",
              "reason_codes",
              "required_role",
              "expires_at",
              "obligations",
              "execution_capability"
            ],
            "properties": {
              "approval_request_id": {
                "type": "string",
                "format": "uuid"
              },
              "status": {
                "const": "PENDING"
              },
              "reason_codes": {
                "type": "array",
                "minItems": 1,
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "required_role": {
                "type": "string",
                "enum": [
                  "OWNER_ADMIN",
                  "OPS_APPROVER",
                  "OPERATOR",
                  "ACCOUNTANT"
                ]
              },
              "expires_at": {
                "type": "string",
                "format": "date-time"
              },
              "obligations": {
                "type": "array",
                "items": {
                  "type": "string",
                  "pattern": "^[A-Z0-9_]+$"
                }
              },
              "execution_capability": {
                "type": "string",
                "pattern": "^[A-Z0-9_]+$"
              }
            }
          }
        }
      }
    ]
  }
},
} as const;

export type OperationDefinition = (typeof OPERATIONS)[keyof typeof OPERATIONS];
