#!/usr/bin/env python
"""Generate the staff console's service-worker precache list.

There is no bundler here, so a list that would normally be build output has to live in the
repository. It must contain every static asset of the shell and nothing else — in particular never
an API path, because caching a customer's data on a shared counter device is exactly what the
console's privacy gate exists to prevent.

A hand-maintained list drifts the moment somebody adds a module, and a drifted list fails silently:
the console still works online, and only stops loading offline, which nobody tests. So the list is
derived from what is actually on disk, and ``--check`` fails CI on drift.

Usage::

    uv run python scripts/generate_staff_console_manifest.py
    uv run python scripts/generate_staff_console_manifest.py --check
"""

from __future__ import annotations

import argparse
import sys
from hashlib import sha256
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "apps" / "web"
SERVICE_WORKER = WEB / "sw.js"

#: Extensions that belong to the shell. Anything else under ``apps/web`` is not a browser asset.
SHELL_SUFFIXES = {".js", ".css", ".webmanifest", ".svg"}

#: The worker itself is fetched out of band by the browser, and a worker that cached itself could
#: not be replaced.
SHELL_EXCLUDE = {"sw.js"}


def shell_files() -> list[Path]:
    """Every static asset under ``apps/web``, in a stable order."""

    return [
        path
        for path in sorted(WEB.rglob("*"))
        if path.is_file()
        and path.suffix in SHELL_SUFFIXES
        and path.relative_to(WEB).as_posix() not in SHELL_EXCLUDE
    ]


def shell_entries(files: list[Path]) -> list[str]:
    """The paths a browser will request, including the directory index."""

    return ["/staff/", *(f"/staff/{path.relative_to(WEB).as_posix()}" for path in files)]


def shell_fingerprint(files: list[Path]) -> str:
    """A digest over every shell file's name and bytes.

    The cache name is derived rather than hand-bumped because the alternative has already failed
    once here: the previous worker was pinned at ``staff-shell-v3`` and still precached a stylesheet
    that no longer exists, which makes ``addAll`` reject and installation fail silently. A name that
    changes whenever any byte of the shell changes means an old cache is always evicted and a stale
    module can never be served offline after a deploy.
    """

    digest = sha256()
    digest.update((WEB / "index.html").read_bytes())
    for path in files:
        digest.update(path.relative_to(WEB).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()[:12]


def render(entries: list[str], fingerprint: str) -> str:
    listed = "\n".join(f'  "{entry}",' for entry in entries)
    return f"""// GENERATED by scripts/generate_staff_console_manifest.py — do not edit by hand.
//
// The shell, and only the shell. This worker never writes a response into the cache, so no API
// payload, no customer name and no draft message can survive on the device. A staff phone is
// shared, is often unlocked, and leaves the shop; the console's offline story is therefore "the
// interface loads and tells you it cannot reach the server", never "your data is still here".

const CACHE = "staff-shell-{fingerprint}";

const SHELL = [
{listed}
];

self.addEventListener("install", (event) => {{
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(SHELL)));
  self.skipWaiting();
}});

self.addEventListener("activate", (event) => {{
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
}});

self.addEventListener("fetch", (event) => {{
  const url = new URL(event.request.url);
  // Anything outside the shell path — every API call included — is left entirely alone. The worker
  // does not proxy it, does not read it, and has no branch that could cache it.
  if (event.request.method !== "GET") return;
  if (url.origin !== self.location.origin) return;
  if (!url.pathname.startsWith("/staff/")) return;

  event.respondWith(
    fetch(event.request).catch(() =>
      caches.match(event.request).then((hit) => hit || Response.error()),
    ),
  );
}});
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when the file is out of date instead of rewriting it",
    )
    arguments = parser.parse_args()

    files = shell_files()
    content = render(shell_entries(files), shell_fingerprint(files))
    current = SERVICE_WORKER.read_text(encoding="utf-8") if SERVICE_WORKER.exists() else ""

    if current == content:
        if arguments.check:
            print("staff console shell manifest is current")
        return 0

    if arguments.check:
        print(f"STALE: {SERVICE_WORKER.relative_to(ROOT)}", file=sys.stderr)
        print("Run: uv run python scripts/generate_staff_console_manifest.py", file=sys.stderr)
        return 1

    SERVICE_WORKER.write_text(content, encoding="utf-8")
    print(f"wrote {SERVICE_WORKER.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
