"""Generate fixed OpenClaw tool metadata from the sole normative OpenAPI registry."""

from __future__ import annotations

# Put this directory on sys.path before importing the workspace bootstrap, so the script
# behaves identically whether it is run as __main__ or loaded by file path from a test.
import sys as _sys
from pathlib import Path as _Path

_sys.path.insert(0, str(_Path(__file__).resolve().parent))

import json
from pathlib import Path

import workspace_env  # noqa: F401  # keep first: puts the workspace on sys.path
from nha_trang_laundry_contracts import load_agent_tool_registry

ROOT = Path(__file__).resolve().parents[1]
OPENAPI = ROOT / "specs/contracts/agent-tools-v1.openapi.yaml"
OUTPUT = ROOT / "runtime/openclaw/public-cell/plugin/src/operation-contracts.ts"


def typescript_source() -> str:
    registry = load_agent_tool_registry(OPENAPI)
    entries: list[str] = []
    for operation, contract in registry.operations.items():
        payload = {
            "operationId": operation.value,
            "toolName": contract.tool_name,
            "method": contract.method,
            "path": contract.path,
            "summary": contract.description or operation.value,
            "pathParameters": list(contract.path_parameters),
            "headerParameters": list(contract.header_parameters),
            "parameters": contract.model_argument_schema,
            "successStatus": contract.success_status,
            "successResponse": contract.success_response_schema,
        }
        encoded = json.dumps(payload, ensure_ascii=False, indent=2)
        entries.append(f"  {json.dumps(operation.value)}: {encoded},")
    return (
        "// Generated by scripts/generate_agent_tool_plugin.py. Do not hand edit.\n"
        "// Model parameters intentionally exclude all path/header binding fields.\n\n"
        "export const OPERATIONS = {\n" + "\n".join(entries) + "\n} as const;\n\n"
        "export type OperationDefinition = (typeof OPERATIONS)[keyof typeof OPERATIONS];\n"
    )


def main() -> None:
    expected = typescript_source()
    if OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == expected:
        print(f"Agent tool plugin contract is current: {OUTPUT.relative_to(ROOT)}")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
